### ISSUE TITLE
What are the next steps after installing the package

### ISSUE THREAD

**Issue by Panix84** [rennokki/chargeswarm#20]
Hello,
I have read the documentation and understand the methods and all but I am a bit confused as to what are the next steps after installing the package? I am a bit new to all this, so my question might be something obvious but unfortunately not to me, so any guidance would be greatly appreciated.
For example, do I somehow retrieve the form for a plan from chargebee (the “hosted pages” as it calls them), were do I get the Braintree token from etc.?

**Comment by rennokki** [comment]
Hey @Panix84,

Chargebee is a service that helps you handle billing for your SaaS applications. It can be found here: https://www.chargebee.com. This package does not help you build locally a SaaS handler like Chargebee does, but my other package: https://github.com/rennokki/plans does.

Chargebee is not a payment system, to be clear. Chargebee just handles invoices, receipts, customers and plans and the payment is done by using Stripe, Braintree or other payments which are presented here: https://www.chargebee.com/payment-gateways/

This package is a wrapper to use Chargebee in your projects without dealing directly with their API or to build your own.

**Comment by Panix84** [comment]
Ahhh ok got it. So basically I create a billing form using ie the Braintree API integration and the package you created to sync the subscriptions between the website and the platform. After that I play with the webhooks to handle modifications by the admin on the platform. Ok got it.

I asked you because I thought that chargebee somehow provided a turn key solution with firmware that have Braintree integrated already and I couldn't figure out how.

Well thanks a lot for your reply and you time.

Have a nice day.

⁣Με εκτίμηση,
Παναγιώτης Αγαπίου​
